version: '3'

services:

  # App Service
  app:
    build:
      context: .
      dockerfile: docker/app/dev/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./:/app
    depends_on:
      - redis
      - db
      - auth
    environment:
      REDIS_URL: redis:6379
    networks:
      - backend
    container_name: wallche_api
    env_file: .env

  # Redis Service
  redis:
    image: "redis:alpine3.12"
    container_name: wallche_redis
    restart: unless-stopped
    networks:
      - backend
    env_file: .env
  db:
    image: mariadb:10.5.8-focal
    container_name: wallche_db
    restart: unless-stopped
    ports:
    - 3306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - backend
    env_file: .env

  auth:
    build:
      dockerfile: ./docker/auth/Dockerfile
      context: .
    container_name: wallche_auth
    working_dir: /app
    ports:
      - "7002:3000"
    env_file: .env
    depends_on:
      - redis
      - db
    networks:
      - backend
      - default

networks:
  backend: